name: deploy to ali cloud

on:
  push: # 提交 pr 的时候触发部署
    branches:
      - main # 触发分支为 main 分支
    paths:
      - '**/*'  # 监听所有文件变更

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 部署到阿里云服务器
      - name: deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: |
            sh /opt/chat/update_chat.sh ai-server
